FROM python:3

# prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONUNBUFFERED 1

ARG DJANGO_SETTINGS_MODULE
ENV DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

ARG DJANGO_SECRET_KEY
ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY

ARG DJANGO_DB_PASSWORD
ENV DJANGO_DB_PASSWORD=$DJANGO_DB_PASSWORD

WORKDIR /app/requirements

COPY requirements/base.txt .

COPY requirements/production.txt .

RUN pip install -r production.txt

WORKDIR /app

COPY . .