FROM python:3

# prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONUNBUFFERED 1

WORKDIR /app/requirements

COPY requirements/base.txt .

COPY requirements/development.txt .

RUN pip install -r development.txt

WORKDIR /app

COPY . .