# Generated by Django 3.1.7 on 2021-04-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['text']},
        ),
    ]
