# Generated by Django 3.1.7 on 2021-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210403_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
