# Generated by Django 3.1.7 on 2021-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_auto_20210318_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
