# Generated by Django 3.1.7 on 2021-03-18 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_auto_20210318_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='active',
        ),
    ]
