# Generated by Django 3.1.7 on 2021-03-19 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chat.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20210318_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='InvitationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('valid_due', models.DateTimeField(default=chat.models.get_inivite_key_expire_date)),
                ('give_admin', models.BooleanField(default=False)),
                ('only_for_this_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                                         to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
