# Generated by Django 3.1.7 on 2021-03-25 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0012_auto_20210325_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitationKey',
            new_name='RoomInviteKey',
        ),
    ]
