# Generated by Django 3.1.7 on 2021-03-25 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0014_auto_20210325_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominvitekey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roominvitekey_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roominvitekey',
            name='only_for_this_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roominvitekey_only_for_this_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
