# Generated by Django 3.1.7 on 2021-03-27 20:15

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210325_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominvitekey',
            name='key',
            field=models.TextField(default=chat.models.get_invite_key_string, unique=True),
        ),
    ]
